### ISSUE TITLE
6章: Markdownファイル中のLaTeX記法によるω (`\omega`) がPDFにそのまま出力されている

### ISSUE THREAD

**Issue by t-sin** [tomoyanonymous/hakuron#7]
つまりこういう表示になっています:
![mimium-hakuron-chap6-omega](https://user-images.githubusercontent.com/4403863/191460884-b04ab00b-401a-47c3-9bfb-9c94724c32db.png)

[こちらの論文の情報ページ](https://www.researchgate.net/publication/267702263_A_classical_version_of_system_F_o)によれば`System Fω`(ωは下付きなんですね)なのでたぶんこれをやろうとしていると思うのですが、意図と違う表示になっていそうです。6章のファイル自体はMarkdownなので挙動不明で、かつビルド環境を容易する元気がなかったためissueとしました。

**Comment by tomoyanonymous** [comment]
ありがとうございます。
書いてる途中まではイタリックにするべき場所を結構tex直書きでやっていたのを途中で直したんですよね。
その際にここを間違えて直してしまっていたようです。直しましょう

https://github.com/tomoyanonymous/hakuron/commit/f59c5244437f23a542d384626dd2f45704218dbd#diff-81de351d2e187601e74d00f7ff545181d2baf97dbc177003017c00e389c184f7L426
